# -*- coding: utf-8 -*-
"""antecessoresucessor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174LX3LsPHwfGx7-oO7MQDd7YAOJgB759

Código para gerar o antecessor e o sucessor de um numero
"""

num=int(input('digite um num:'))

print('o sucessor é {} e o antecessor é {}:'.format(num+1,num-1))