# -*- coding: utf-8 -*-
"""AntecessoreSucessor1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **InteiroAoQuadrado** 😦

# Nova seção
"""

numero= int(input("Digite o número: "))
antecessor = numero - 1
sucessor = numero + 1

print(antecessor,numero,sucessor)