# -*- coding: utf-8 -*-
"""antecessor e sucessor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dl7jjrTIPEFYJNam-QLkUdhDc41RLpl
"""

a=float(input("Digite o número: "))

print(a-1,a+1)