# -*- coding: utf-8 -*-
"""Aprovado e reprovado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzKBS5XuE69leNHbkJBqii-4qq6liPCL
"""

Nota=int(input("Digite sua nota:"))
if Nota>6:
  print("Aprovado")
else:
   print("Reprovado")