# -*- coding: utf-8 -*-
"""AreaEPerimetro1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **InteiroAoQuadrado** 😦

# Nova seção
"""

base= float(input("Digite a base: "))
altura= float(input("Digite a altura: "))

area = base * altura
perimetro = 2.0 * (base + altura)
4
print("Area do retangulo = ", area)
print("Perimetro do retangulo = ", perimetro)