# -*- coding: utf-8 -*-
"""aumentofelipe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

salario= float(input("Digite o valor do salário: "))
percentual = float(input("Digite o aumento percentual: "))

calculo = salario * (percentual /100)
aumento = calculo + salario

print("Salário atual: ", aumento)