# -*- coding: utf-8 -*-
"""Calculo da hipotenusa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPh8Up3Byuvz3emUDxJeoz42MYEE7IyE
"""

a=2
b=3
resultado = (a*a)+(b*b)
print(resultado*resultado)