# -*- coding: utf-8 -*-
"""CalculadorDePrestações.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179ve11gYnL-GgYbR3XA3Fkp3UZrSmv_h
"""

Taxa=float (input("Digite sua taxa:"))
Tempo=int (input("Digite seu tempo:"))
Valor=int (input("Digite seu valor:"))
Prestação = Valor + (Valor*(Taxa/100)*Tempo)
print ("Este é o valor da sua prestação",Prestação)