# -*- coding: utf-8 -*-
"""Calculador de Área e Perímetro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqjT3LfGSz1aQOsN6m0LSsMkyPpUfst6
"""

Base=int(input("Escolha a area da sua base:"))
Altura=int(input("Escolha a area da sua altura:"))
Perimetro = Base*2+Altura*2
Area = Base*Altura
print(Perimetro,"é o valor do seu perimetro")
print(Area,"é o valor da sua area")