# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O7xq4UyezB_ur7L7uy_DQMIck2iIW7bX
"""

a=2

b=4

print (a+b)

print(b-a)

print(b/a)

print(a*b)