# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199BG0hbh_eR9jvf6dUsInNqaA3mxtLSo

Calculadora com as funções soma, sobtração divisão e multiplicação
"""

val1,operacao,val2=input('operação:').split()

print(val1,operacao,val2)

val1=int(val1)

val2 = int(val2)

resultado=[]

if operacao == '+':
  resultado = val1+val2

elif operacao == '-':
  resultado = val1-val2

elif operacao == '*' or operacao=='x':
  resultado = val1*val2

elif operacao == '/':
  resultado = val1 / val2





print(resultado)

