# -*- coding: utf-8 -*-
"""circulofelipe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

r= float(input("Digite o valor do raio do circulo: "))

area = 3.14 * (r * r)

print("AREA = ", area)