# -*- coding: utf-8 -*-
"""de maior e de menor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvueXl0u99l0U5tqmgfXODOu9oDj9byY
"""

ano=int(input("digite em que ano voce esta:"))
idade=int(input("digite o ano que voce nasceu:"))

numeros = ano-idade

print("esta é sua idade:",numeros)

if numeros>=18:
  print("voce é maior")
else:
  print("voce é menor")