# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZZsvTnJrX7tbzKSRFXaNJq97zaqjdKQ
"""

# Numero decimal e seu quadrado

valor_uni=float(input("(sete):"))

print(valor_uni)

print(valor_uni*2)

