# -*- coding: utf-8 -*-
"""DigiteSeuNumeroDecimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kjlj_He9aep-sjvwGeNCCcCYPBIhOJDo
"""

valor_uni=float(input("Digite o valor:"))

print(valor_uni)