# -*- coding: utf-8 -*-
"""DigiteSeuNome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvLcEyLyOO8DbsZps1oZDuCm5OG7YYTR
"""

nome = input("Digite seu none:")

print("Seu nome é:",nome)