# -*- coding: utf-8 -*-
"""Divisão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGkcge1B1TKmIcp8o70YWM4Xy0k9Y-Q6
"""

a=1

b=2

print(a/b)

