# -*- coding: utf-8 -*-
"""exibição de números

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNKF7VBIrrJ8flLmAWI-Go9R4eaCmL0q
"""

a=float(input("Número 1: "))

b=float(input("Número 2: "))

print("O usuario digitou: ",a,b)