# -*- coding: utf-8 -*-
"""FacaSeuCadastro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAZ857ECkejMboYT2UrujwnKutPKNri4
"""

caractere1=int(input("Digite seu primeiro numero:"))
caractere2=int(input("Digite seu segundo numero:"))
print ("O usuario digitou:",caractere1, "e", caractere2)