# -*- coding: utf-8 -*-
"""hipotenusa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

a = float(input("Digite o valor do cateto A: "))
b = float(input("Digite o valor do cateto B: "))

hipotenusa = a*a + b*b


print("Hipotenusa: ", hipotenusa)