# -*- coding: utf-8 -*-
"""hipotenusa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmDHArC9L_s333gQ97Jt5HYhjfoKmgDs
"""

a=float(input("Cateto A: "))

b=float(input("Cateto B: "))

c=float((a*a)+(b*b))

print("O valor da hipotenusa ao quadrado é: ",c)