# -*- coding: utf-8 -*-
"""InteiroAoQuadrado1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **InteiroAoQuadrado** 😦

# Nova seção
"""

numero = int(input("Digite um número inteiro: "))
resultado= numero * 2
print(resultado)