# -*- coding: utf-8 -*-
"""LeitorAoQuadrado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIhCEFqeWvfC_Xoybo2k3nD-l28kdqTQ
"""

#primeiro definir meu metodo e digitar meu numero
numero=int (input("Digite seu numero:"))
#resultado da conta ao quadrado
print ("Esse é o seu numero ao quadrado:", numero*numero)