# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yf7U8J1M-NaLllbnWYmMRld3bTwOnfKR
"""

# leitor de caracter

usuario1 = int(input("digite aqui"))

usuario2 = int(input("digite aqui2"))

print ("usuario digitou:",usuario1)

print ("usuario digitou:",usuario2)

