# -*- coding: utf-8 -*-
"""maioremenor1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2okllqdloPvRTOY_Jr-dIg6LEdMue-J
"""

media = soma = valor = 0

for i in range(10):
    valor = int(input(f"Digite o {i+1}º valor inteiro: "))

    if i == 0:
      maior = menor = valor
    else
      if valor > maior:
        maior = valor
      if valor < menor:
        menor = valor

      soma += valor
      media += soma / 10

print("O maior valor digitado é = ", maior)
print("O menor valor digitado é = ", menor)
print("A média dos valores digitados é = ", media)