# -*- coding: utf-8 -*-
"""maiordeidadefelipe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

ano_atual = int(input(print("Digite o ano atual: ")))
ano_nascimento = int(input(print("Digite o ano de nascimento: ")))

idade = ano_nascimento - ano_atual

if idade < 18:
  print("Você é maior de idade")
else:
  print("Você é maior!")