# -*- coding: utf-8 -*-
"""maiornumerofelipe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

n1 = float(input("Digite o primeiro número: "))6
n2 = float(input("Digite o segundo número: "))

if n1 > n2:
    print("o número  maior é: ", n1)
else:
    print("o número maior é:", n2)