# -*- coding: utf-8 -*-
"""medianotasfelipe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a primeira nota: "))

media = (nota1 + nota2) / 2

if media < 6:
    print("Reprovado:", media)
else:
    print("Aprovado:", media)