# -*- coding: utf-8 -*-
"""Media da soma aritimetica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byv9MH48JDyMqGYd77W4bZF44pmO4UFK
"""

a=3
b=5
c=6
Soma=int(a+b+c/3)
print ("Essa é a media aritietica:",Soma)