# -*- coding: utf-8 -*-
"""Multiplicação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fO1RXADcqIQYvCqzzhY-zk0U2HNTYFj
"""

a=1

b=2

print(a*b)

