# -*- coding: utf-8 -*-
"""média

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i535AoHQ6UvEOVMXqRv8xJo8lIlIoofO
"""

nota1=float(input("Nota 1: "))

nota2=float(input("Nota 2: "))

nota3=float(input("Nota 3: "))

media=float((nota1+nota2+nota3)/3)

print("Sua média é: ",media)