# -*- coding: utf-8 -*-
"""NumeroSucessorEAntecessor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADM0gak_p_Bcj6i5_qyD4K1YxtuOuYcE
"""

numero=int (input("digite seu numero:"))
print("Esse é o antecessor:",numero-1,)
print("esse é o sucessor:", numero+1)