# -*- coding: utf-8 -*-
"""Números impares e pares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITdvn3nFBp_OXdHx50Vi-hdKO7ubwCXE
"""

numero=int(input("digite seu numero:"))

if numero % 2 == 0:
    print ("O numero é par")
 else:
    print("o numero é impar")