# -*- coding: utf-8 -*-
"""númerosiguaisfelipe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **Operadores Aritméticos** 😦

# Nova seção
"""

n1 = int(input(print("Digite o primeiro número: ")))
n2 = int(input(print("Digite o segundo número: ")))

if n1 == n2:
  print(n1, " e ",n2," são iguais")
else:
  print(n1, " e ",n2," não são iguais")