# -*- coding: utf-8 -*-
"""Perimetro e área

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2F0WOGBG0EiXz62OqMqxdPmRLb7qHwh
"""

a=float(input("Base: "))

b=float(input("Altura: "))

print("Perimetro: ",a+a+b+b)

print("Área: ",a*b)