# -*- coding: utf-8 -*-
"""Perímetro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp6QYiXRXdsOwOnkqtn4QrKMqUVF6UeE
"""

base = int(input("Digite o valor da base:"))

altura = int(input("DIgite o valor da altura:"))

perimetro = base*2+altura*2

area = base*altura

print("O perímetro do retângulo é:", perimetro )
print("A área do retângulo é:", area)