# -*- coding: utf-8 -*-
"""Porcentagem do salario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2PrLbk1VFkxbeNR4S4h2Rwbkn01-kRv
"""

salario=int(input("Informe do seu salario:"))
porcentagem=(10/100)

print(salario+(salario*porcentagem))