# -*- coding: utf-8 -*-
"""Prestação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qroL2GdFuA2FjZSkHkagCDquC47o9xPi
"""

valor = int(input("Digite seu valor:"))
taxa = float(input("A taxa é de:"))
tempo = int(input("Defina o tempo:"))
prestacao = valor+(valor*(taxa/100)*tempo)
print("O valor da sua prestação é:", prestacao)