# -*- coding: utf-8 -*-
"""Print e Input

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RpEZMnNzpHXfpCQbkbJ2tZSd5LDbLCuZ
"""

nome=input("Digite seu nome:")

print("Seu nomé é:",nome)

valor_uni=int(input("Digite seu valor: "))

valor_uni

quantidade=int(input("Digite o valor: "))

valor_uni*quantidade

quantidade*valor_uni

