# -*- coding: utf-8 -*-
"""Projeto Inicial Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1clYtjqKhaJ7w5Y7eErM5_vDIlnUWTqS8

Aula 15/04/2024 - Introdução ao Colab
"""

print('Hello Word!')

a=1

b=2

print(a+b)

