# -*- coding: utf-8 -*-
"""quadrado do número

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhJEku_Z6GVFo9P_n7B5xbL_TzG-dRNQ
"""

a=float(input("Digite um número: "))

print(a*a)