# -*- coding: utf-8 -*-
"""qualodigito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126G3Bdg9JaqXGwgLUFY6g-SdwZaP293L

Código para dizer que número o usuário digitou
"""

a,b=input('digite dois caracteres:').split()

print('o usuário digitou "{}" e em seguida "{}"'.format(a,b))