# -*- coding: utf-8 -*-
"""Read Int Number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Ayyo7Lh0UqnilSZIBWPyLOxBlShuaA1
"""

Valor=int(input("Digite seu valor:"))

print("Seu valor é:",Valor**2)