# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0zuPlL57GER8Y4rT5GMi8wHlwqfK5YF
"""

# Tarefa 02 - Somador

a=2

b=4

print (a+b)

print (b-a)

print (a/b)

print (a*b)

