# -*- coding: utf-8 -*-
"""Subtração

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRaPTZrSDq1PJuDblWlkl1Dc4j2r3SDZ
"""

a=1

b=2

print(a-b)

