# -*- coding: utf-8 -*-
"""Sucessor e Antecessor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oE3dsLkG5o7tM-dFNjE3Hqrv2I2LJKy
"""

valor = int(input("Digite seu valor:"))

print("O sucessor deste valor é:", valor+1)
print("O antecessor deste valor é:", valor-1)