# -*- coding: utf-8 -*-
"""temperaturafebril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2okllqdloPvRTOY_Jr-dIg6LEdMue-J
"""

qntd_pessoas = int(input("Quantas pessoas serão analisadas? "))
soma_temperaturas = 0
total_pessoas = 0

for i in range(1, qntd_pessoas + 1):
    temperatura = float(input(f"Digite a temperatura da pessoa {i} (em Celsius): "))
    if 35 <= temperatura <= 42:
        if temperatura < 37.2:
            print("Temperatura normal")
        elif 37.3 <= temperatura < 38:
            print("Estado febril")
        elif 38 <= temperatura < 39:
            print("Com febre")
        else:
            print("Com febre alta")

        soma_temperaturas += temperatura
        total_pessoas += 1
    else:
        print("Por favor, digite uma temperatura corporal válida (entre 35 e 42 graus Celsius).")

media_temperatura = soma_temperaturas / total_pessoas

print("Total de pessoas analisadas:", total_pessoas)