# -*- coding: utf-8 -*-
"""Teste1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

*Aula 15/04/2024* - Prof. Tom
Comando **Print** 😦
"""

# Comando para imprimir
print('Hello World!')

a=1

b=2

print('a+b')

print(a+b)