# -*- coding: utf-8 -*-
"""teste1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmrVdeZuIIUaMbRx3rDsyJuQmy52xzSk

**Aula 15/04/24** - Prof. Tom
comando **print**
"""

#comando para imprimir
print('hello world')

a=1

b=2

print('a+b')

print(a+b)