# -*- coding: utf-8 -*-
"""Teste1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWJpSsrHca21Xd7IRoyyA5vFgCts8uzL

Aula 15/04/24 - prf. Tom
Comando **print**
"""

# Comando para imprimir
print ('Hello World!')

a=1

b=2

print(a+b)

