# -*- coding: utf-8 -*-
"""Two String

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtNWIFZX2hzkO8uu4XGdqTJSSLC904_J
"""

valores = int(input("valor1:")), input("valor2:")

print("O usuário digitou:", valores)