# -*- coding: utf-8 -*-
"""Valor de um volume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVmmyKajHw8O_RsPeHY5LmFl8NgDMmux
"""

volume=int(input("digite o raio:"))
raio=int(input("digite o raio:"))
altura=int(input("digite a altura:"))

volume = 3,14 * raio*raio * altura
print ("este é o valor do seu volume:",volume)