# -*- coding: utf-8 -*-
"""Valor maior e valor menor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17x-RE49_U5Zgz_YGo2drGKtut5bU8-3O
"""

num=int(input("Digite seu primeiro valor:"))
nois=int(input("Digite seu segundo valor:"))

if num > nois:
  print("O primeiro numero é maior")

if nois > num:
  print("O segundo numero é maior")