# -*- coding: utf-8 -*-
"""valor da prestação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VsjnhTIz9uO0sYw6_ktpiIDD5ftkuKV
"""

valor=float(input("Digite o valor da parcela: "))

taxa=float(input("Digite o valor da taxa: "))

tempo=float(input("Digite o tempo: "))

prestacao=valor+(valor*(taxa/100)*tempo)

print("O valor da prestação é: ",prestacao)