# -*- coding: utf-8 -*-
"""ValorPrestacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbVo0HElr4A3B33wZ9Ro_CCNcVoZci6m

* **Aula 17/04/2024** - Prof. Tom
Comando **InteiroAoQuadrado** 😦

# Nova seção
"""

# Solicita os dados de entrada ao usuário
valor=int(input("Digite o valor da prestação: "))
taxa= float(input("Digite a taxa da prestação: "))
tempo= int(input("Digite o tempo de atraso(em meses): "))

# Calcula o valor da prestação em atraso
valor_prestacao= valor + (valor * (taxa/100) * tempo)

# Exibe o resultado
print("O valor da prestação em atraso é: ",valor_prestacao)