# -*- coding: utf-8 -*-
"""Verificar números iguais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObaElI2iW5ijEUgL3E52fFvU2vgyCmLD
"""

numero1=int(input("digite seu primeiro numero:"))
numero2=int(input("digite seu segundo numero:"))

if numero1==numero2:
  print("os numeros sao iguais")
else:
  print("os numeros sao diferentes")