# -*- coding: utf-8 -*-
"""areaeperimetro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2fuzG-qqAUsxh0MdNMuU7sNcD6MdKTN

Programa para calcular o perímetro e area de um retângulo
"""

b,h=input('insira a base e a altura de um retângulo para caulcular seu perímetro e area:').split()

b=float(b)

h=float(h)

print('o perímetro de seu retângulo é: {} \nA area de seu retângulo é: {}'.format(2*b+2*h,b*h))