# -*- coding: utf-8 -*-
"""Elevado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZzemsBzVaonN_y_RpcDVNteaev8Nevz

Programa para criar elevação ao quadrado
"""

numelevado=int(input('inputnum:'))

elevado=numelevado**2

print(elevado)

