# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQmApdNawjNMeX8l_3-MGG2e0fDO5XOl
"""

#ler numeros inteiros antecessor e sucesor

valor_uni=float(input("(seis):"))

print(valor_uni)

print(valor_uni-1)

print(valor_uni+1)

