# -*- coding: utf-8 -*-
"""Placar do jogo e quem ganhou ou empatou.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWFll5LFWntppHc2YZCaTjWOtBAJjoFG
"""

time1=int(input("Digite o saldo de gol do primeiro time time:"))
time2=int(input("Digite o saldo de gol do segundo time:"))

if time1>time2:
  print("Time 1 ganhou o jogo")
if time2>time1:
  print("Time 2 ganhou o jogo")
elif time1==time2:
  print("os times empataram")